version: '3.7'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/backend:/var/www
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    stdin_open: true
    command: npm start
    volumes:
      - ./services/frontend:/var/www
      - '/var/www/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  next-app:
    build:
      context: ./services/next-app
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./services/next-app:/var/www
      - '/var/www/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - backend
volumes:
  postgres_data: